### ISSUE TITLE
as a wajug fan, I'd like to easily promote an event on social media

### ISSUE THREAD

**Issue by srondal** [WAJUG/new-wajug.github.com#13]
add the possibility to tweet/FB directly from the event page, with a pre-defined message

**Comment by eloudsa** [comment]
Share buttons are now visible for each post.

I still have to allow shares on Facebook.

**Comment by srondal** [comment]
for the look & feel of these share buttons, i suggest to use the icons from fontawesome, which is what is already used on the home page and in the header
https://fortawesome.github.io/Font-Awesome/

also, visually speaking, it would make sense to align these "share buttons" (on the same line?) with the registration button (to be re-styled), this way we woud have a logical "inscrivez-vous    -    parlez en"

**Comment by srondal** [comment]
Stephane to send facebook credentiels (dev account)

**Comment by eloudsa** [comment]
Share buttons located at the right of the "Enregistrez-vous".
The share to FB will have to be tested when the site will be live.
